### PR TITLE
Remove circleci deprecated message

### PR DESCRIPTION
**Pull request by lolboysg**
This is the PR aiming to fix the issue #469 by removing deprecated messages from the docker images being used.

### CODE REVIEW

**Comment by mrnerdhair** [comment]
No luck so far: https://app.circleci.com/pipelines/github/shapeshift/hdwallet/2056/workflows/3fb5f1b4-b485-44bf-8d30-33426d74a493/jobs/4043

**Comment by lolboysg** [comment]
yeah I see this I'm looking into it right now

**Comment by mrnerdhair** [comment]
Better, but something's still busted about the environment: https://app.circleci.com/pipelines/github/shapeshift/hdwallet/2058/workflows/f6f4e6ca-9128-4be3-bdc9-3161d800634e/jobs/4045

My gut says this has something to do with `jest` overriding various globals, but I'm not sure.

**Comment by lolboysg** [comment]
If it was jest, why would it stop working with this image and not the previous ones @mrnerdhair

**Comment by lolboysg** [comment]
Well looks like it works now

**Review by mrnerdhair — APPROVED** [review]
Looks good to me!

**Pull request merged**
