### PR TITLE
feat: pass full AddEthereumChainParameter params in ethSwitchChain

### PR DESCRIPTION
**Pull request by gomesalexandre**
## Description

This accepts the full `AddEthereumChainParameter` params in `ethSwitchChain()`.

Now that chain-adapters support `getDisplayName()` (https://github.com/shapeshift/lib/pull/880), we can build an object containing the full [`AddEthereumChainParameter`](https://github.com/shapeshift/hdwallet/blob/8186e4757fee8872be3bcf43f73a6c3d66c795ba/packages/hdwallet-core/src/ethereum.ts#L112) object that the [`wallet_addEthereumChain` JSON-RPC call](https://docs.metamask.io/guide/rpc-api.html#unrestricted-methods) expects to add a chain, so we can both switch chain and add it if not yet in user wallet, programmatically.

### CODE REVIEW

**Review by elmutt — APPROVED** [review]

**Review by 0xApotheosis — APPROVED** [review]

**Review by 0xApotheosis — DISMISSED** [review]

**Review by pastaghost — DISMISSED** [review]

**Review by 0xApotheosis — APPROVED** [review]
Re-approving post-publish.

**Comment by gomesalexandre** [comment]
> Re-approving post-publish.

Looks like this was out of date and previous version publish (https://github.com/shapeshift/hdwallet/commit/41bed2d8f10724f78d39425e05711d8882a21c81) invalidated this, 8539829bc06d424b1a2bee0c183684fd2946d17c will publish v1.30.0 including both this and https://github.com/shapeshift/hdwallet/commit/27a4fd31b590051a18cec2387a4574ec05cb546d (cc @pastaghost)

**Review by pastaghost — APPROVED** [review]

**Review by 0xApotheosis — APPROVED** [review]

**Comment by 0xApotheosis** [comment]
@gomesalexandre integration test fail in `master` now with this merged? 🤔

**Comment by gomesalexandre** [comment]
> @gomesalexandre integration test fail in `master` now with this merged? 🤔

Bisected locally and integration tests don't seem to pass on any of the latest commits, even for commits that are supposed to have passed remote CI - that's with `yarn clean && yarn build && yarn test:integration` to make sure I have cleanly installed npm packages and built packages.

Authored https://github.com/shapeshift/hdwallet/pull/556/commits/b98f15490076286d9542fabf4046c81c474fac25 which should do the trick for the purpose of fixing these errors. I'm having other errors locally but they seem to be caused by caching issues, testing things a bit more to see if these are also errors to be tackled in that PR.

**Pull request merged**
