### PR TITLE
feat: add XDeFi Adapter (fixed build)

### LINKED ISSUE #407: XDEFI wallet support hdwallet
taking over @loxator's PR as he's out this week

### PR DESCRIPTION
**Pull request by mrnerdhair**
Migrated from #388; applies build fix and review suggestions. Fixes #407.

### CODE REVIEW

**Comment by mrnerdhair** [comment]
@loxator I've got the build working now, but it's failing some test cases. Any idea what's going on?

**Comment by loxator** [comment]
Thanks @mrnerdhair ! Seems like an issue with the saved snapshots. Sadly, i don't have access to my PC for a week as I'm away, so I won't be able to take a look anytime soon. Will check it first thing when I'm back

**Comment by mrnerdhair** [comment]
No problem at all, and thanks for your work!

**Review by pastaghost — APPROVED** [review]

**Comment by loxator** [comment]
@mrnerdhair , I have fixed the snapshot and the tests are passing. However, I am unsure of how to push to this branch as it seems to be protected. Should I open another PR from my forked repo to this one? Or is there an easier way to push my changes directly to your branch? Thank you for your help!

**Comment by loxator** [comment]
This PR has been migrated to #410 with the working build and fixed tests. Please close it @mrnerdhair and thank you! :pray:

**Comment by 0xdef1cafe** [comment]
closing in favor of https://github.com/shapeshift/hdwallet/pull/410 which is ready to go

**Pull request closed without merging**
